SELECT INGREDIENT_TYPE, SUM(TOTAL_ORDER) as TOTAL_ORDER
FROM (SELECT TOTAL_ORDER, INGREDIENT_TYPE FROM FIRST_HALF F INNER JOIN ICECREAM_INFO I WHERE F.FLAVOR = I.FLAVOR) as T
GROUP BY T.INGREDIENT_TYPE;