SELECT T.BOOK_ID, T.AUTHOR_NAME, DATE_FORMAT(T.PUBLISHED_DATE, '%Y-%m-%d') as PUBLISHED_DATE
FROM (SELECT B.BOOK_ID, 
        A.AUTHOR_NAME, 
        B.PUBLISHED_DATE, 
        B.CATEGORY FROM BOOK B LEFT OUTER JOIN AUTHOR A ON B.AUTHOR_ID = A.AUTHOR_ID) as T
WHERE T.CATEGORY = "경제"
ORDER BY T.PUBLISHED_DATE;